@extends('layout/primary')

@section('content')

<div class="container my-5">
    <div class="row">
        <h1 class="text-center mb-5">Terms and Conditions</h1>
        <p> You are responsible for your log-in credentials and for any activity resulting from the use of your log-in credentials or other activity on your account (“Account”) on the Service. Upon launching the App or the Service, if you do not already have an Account, you will be prompted to create one by providing a username and in some cases a password. You may also be required to provide a valid email address or other information to access or utilize certain applications or features. You represent and warrant that the information you provide to us upon registration and at all other times will be true, accurate, current, and complete. We reserve the right to reject any username or to terminate your username or prevent use of a username in our sole discretion, and without any liability to you. You understand and agree that other users of the Service may have the same username as you, however, users will be differentiated by a number identifier that may or may not be visible to you or other users. You will ensure that your e-mail address is kept accurate and up-to-date at all times. If we allow you to use the App without creating an Account (e.g., if we make available a single-session use feature), any username you select for use in connection with the App will be available for other users after your session ends. You are responsible for maintaining the confidentiality of your log-in credentials and are fully responsible for all activities that occur through the use of your credentials or otherwise on your Account. You agree to notify us immediately if you believe the confidentiality of your log-in credentials has been compromised or if you suspect unauthorized use of your Account. You agree that we will not be liable for any loss or damage arising from unauthorized use of your credentials.</p>
        <p> You agree to receive communications from us electronically, such as email, text, or mobile push notices, or notices and messages on the Service. For any direct marketing messages, we will ensure that we obtain your consent first, and also make it easy for you to opt out — we don’t want to send you messages you don’t want.</p>
        <p> All rights, title and interest in and to all materials that are part of the Service (including, but not limited to, designs, text, graphics, pictures, video, information, applications, software, music, sound and other files, and their selection and arrangement), except for Your Content, collectively referred to as the "Service Materials,” are, as between the Company and you, owned by the Company and/or its third party licensors. You acknowledge and agree that you shall not acquire any ownership rights whatsoever by downloading Service Materials or by purchasing any Virtual Currency or Virtual Goods (each as defined below). You agree that you shall not modify, copy, distribute, frame, reproduce, republish, download, scrape, display, post, transmit, or sell in any form or by any means, in whole or in part, or otherwise exploit the Service Materials without our express prior written permission. You acknowledge that you do not acquire any ownership rights by using the Service or by accessing any Service Materials posted on the Service by the Company, or any derivative works thereof. All rights not expressly granted by these Terms are reserved by the Company and its licensors, and no license is granted hereunder by estoppel, implication or otherwise.</p>
        <p> Any data, text, graphics, photographs and their selection and arrangement, and any other materials uploaded to the Service by you is “Your Content.” You represent and warrant that Your Content is original to you and that you exclusively own the rights to such content, including the right to grant all of the rights and licenses in these Terms without the Company incurring any third party obligations or liability arising out of its exercise of such rights and licenses. All of Your Content is your sole responsibility and the Company is not responsible for any material that you upload, post, or otherwise make available. By uploading, distributing, transmitting or otherwise using Your Content with the Service, you grant to us a perpetual, nonexclusive, transferable, royalty-free, sublicensable, and worldwide license to use, host, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform, and display Your Content in connection with operating and providing the Service. The Company does not guarantee the accuracy, quality, or integrity of any user content posted. By using the Service, you acknowledge and accept that you may be exposed to material you find offensive or objectionable. You agree that the Company will not under any circumstances be liable for any user content, including, but not limited to, errors in any user content, or any loss or damage incurred by use of user content. The Company reserves the right to remove and permanently delete Your Content from the Service with or without notice for any reason or no reason. You may notify the Company of any user content that you believe violates these Terms, or other inappropriate user behavior, by emailing abuse@gopora.com.</p>
    </div>
</div>

@endsection
